# Generated by Django 5.0.6 on 2024-06-04 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acronymizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acronymtoken',
            old_name='preposition',
            new_name='preposition_or_conjunction',
        ),
        migrations.AlterField(
            model_name='acronymtoken',
            name='preposition_or_conjunction',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('ante', 'ante'), ('bajo', 'bajo'), ('cabe', 'cabe'), ('con', 'con'), ('contra', 'contra'), ('de', 'de'), ('desde', 'desde'), ('durante', 'durante'), ('e', 'e'), ('en', 'en'), ('entre', 'entre'), ('hacia', 'hacia'), ('hasta', 'hasta'), ('mediante', 'mediante'), ('o', 'o'), ('para', 'para'), ('por', 'por'), ('según', 'según'), ('sin', 'sin'), ('so', 'so'), ('sobre', 'sobre'), ('tras', 'tras'), ('u', 'u'), ('y', 'y')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
